# This is a basic workflow to help you get started with Actions

name: CI Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#
#      #Execute unit tests
#      - name: Unit Test
#        run: ./gradlew testDebugUnitTest
#
#      #Report test results
#      - name: Android Test Report
#        uses: asadmansr/android-test-report-action@v1.2.0
#        if: ${{ always() }}

#?
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: react-native-community/sdk-setup-action@v2
        with:
          ndk-version: '21.4.7075529'
          sdk-version: '31'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute tests
        run: ./gradlew testDebugUnitTest

      - name: Generate Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          files: '**/TEST-*.xml'



#?
  # This workflow contains a single job called "build"

  #build:
    # The type of runner that the job will run on
   # runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      #- name: Run a one-line script
       # run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
       # run: |
        #  echo Add other actions to build,
         # echo test, and deploy your project.







#name: CI Workflow
#
#on:
#  push:
#  pull_request:
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#
#      #Execute unit tests
#      - name: Unit Test
#        run: ./gradlew testDebugUnitTest
#
#      #Report test results
#      - name: Android Test Report
#        uses: asadmansr/android-test-report-action@v1.2.0
#        if: ${{ always() }}

#name: CI Workflow
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    env:
#      ANDROID_HOME: /usr/local/android-sdk
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup Java
#        uses: actions/setup-java@v2
#        with:
#          java-version: 11
#
#      - name: Setup Android SDK
#        uses: android-actions/setup-android-sdk@v2
#        with:
#          sdk-version: 31
#
#      - name: Build with Gradle
#        run: ./gradlew assembleDebug
#
#      - name: Run Unit Tests
#        run: ./gradlew testDebugUnitTest
#
#      - name: Android Test Report
#        uses: asadmansr/android-test-report-action@v1.2.0
#        if: ${{ always() }}
